### ISSUE TITLE
Found potential runtime exception

### ISSUE THREAD

**Issue by Wushuyi123** [jwpttcg66/redis-game-transaction#6]
Hello,
First of all i want to thank you for sharing your code.
But when I was operating some of my files, there was a runtime exception of the type 'java.lang.IlegalArgumentException'. The runtime exception was from method:
com.redis.util.JdomUtils.getIntArrayAttriValue(org.jdom.Element,java.lang.String)
```
    public static int getIntAttriValue(Element e, String attrName) {
        String attributeValue = e.getAttributeValue(attrName);
        if (attributeValue == null) {
            return -1;
        }
        return Integer.valueOf(attributeValue);
    }

```
it might cause the program to crash. But the caller may not know these problems and may cause the program to crash suddenly. 
so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop. Thank you!
The issue can be reproduced by passing the method with non-number string

**Comment by jwpttcg66** [comment]
thanks for your help
